### ISSUE TITLE
Basic meta data in ElasticSearch

### ISSUE THREAD

**Issue by ablx** [ablx/filex#3]
- [x] Setup ElasticSearch for tests
- [x] Define index structure
- [x] For each file, add the id + file name to the index
